### ISSUE TITLE
Подключение SDK binance

### ISSUE THREAD

**Issue by Sandr0oo** [tsol/test-nuxt3-broker#1]
Привет. Я так понимаю ты используешь [вот эту библиотеку](https://github.com/tiagosiebler/binance). Подскажи, пожалуйста, как ты ее подключил в nuxt? Я попробовал собрать бандл и просто положить его в проект, но выходит такая штука: 
![Code_pEsmJ0MSG2](https://user-images.githubusercontent.com/61181414/218951197-b775773f-a911-4b53-995e-3dc9ee19bea2.png)

**Comment by tsol** [comment]
Не могу помочь, т.к. я использую эту библиотеку чисто на бэкенде. Фронт общается с бэком по вебсокетам, а уже бэк делает запросы.
